# Generated by Django 2.0.3 on 2018-05-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_singlevideo_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlevideo',
            name='views',
        ),
    ]
