# Generated by Django 2.0.3 on 2018-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20180504_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takencourse',
            name='taken_course',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
