# Generated by Django 2.0.3 on 2018-05-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_takencourse_taken_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takencourse',
            name='taken_course_category',
        ),
    ]
