# Generated by Django 2.0.3 on 2018-05-04 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_remove_takencourse_taken_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='takencourse',
            name='taken_course_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
