# Generated by Django 2.0.3 on 2018-05-04 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_takencourse_taken_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takencourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
