# Generated by Django 2.0.3 on 2018-05-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_auto_20180504_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takencourse',
            name='taken_course_category',
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='taken_course_title',
        ),
    ]
