# Generated by Django 2.0.3 on 2018-05-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_auto_20180504_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takencourse',
            name='taken_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Course'),
        ),
    ]
