# Generated by Django 2.0.3 on 2018-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_auto_20180504_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takencourse',
            name='taken_course',
        ),
        migrations.AddField(
            model_name='takencourse',
            name='taken_category_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='takencourse',
            name='taken_course_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='takencourse',
            name='taken_course_image',
            field=models.ImageField(null=True, upload_to='User/TakenCourses'),
        ),
        migrations.AddField(
            model_name='takencourse',
            name='taken_course_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='takencourse',
            name='taken_course_url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
