# Generated by Django 2.0.3 on 2018-05-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_auto_20180504_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takencourse',
            old_name='taken_course',
            new_name='taken_course_url',
        ),
    ]
