# Generated by Django 2.0.3 on 2018-05-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_auto_20180504_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takencourse',
            name='taken_course_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
