# Generated by Django 2.0.3 on 2018-05-05 05:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0049_auto_20180504_2342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='takencourse',
            unique_together={('user', 'taken_course_url')},
        ),
    ]
